# routes.yml
composerDiagnose:
  path:     /composer/diagnose/{site}/{path}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\ComposerController::diagnoseAction', _format: 'json', path: '' }
  requirements: { _format: 'html|json', _method: 'GET' }

composerDumpAutoload:
  path:     /composer/dumpautoload/{site}/{path}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\ComposerController::dumpAutoloadAction', _format: 'json', path: '' }
  requirements: { _format: 'html|json', _method: 'GET' }

composerInstall:
  path:     /composer/install/{site}/{path}/{devMode}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\ComposerController::installAction', _format: 'json', path: '', devMode: 'no-dev' }
  requirements: { _format: 'html|json', _method: 'GET', devMode: 'dev|no-dev' }

composerUpdate:
  path:     /composer/update/{site}/{path}/{devMode}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\ComposerController::updateAction', _format: 'json', path: '', devMode: 'no-dev' }
  requirements: { _format: 'html|json', _method: 'GET', devMode: 'dev|no-dev' }

phpunitFunctional:
  path:     /phpunit/functional/{site}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\PhpunitController::functionalAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

phpunitUnit:
  path:     /phpunit/unit/{site}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\PhpunitController::unitAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

sites:
  path:     /site/list/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\SiteController::listAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitBranch:
  path:     /git/branch/{site}/{repository}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::branchAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitClean:
  path:     /git/clean/{site}/{repository}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::cleanAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitCheckout:
  path:     /git/checkout/{site}/{repository}/{change}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::checkoutAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitFetch:
  path:     /git/fetch/{site}/{repository}/{remote}/{branch}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::fetchAction', _format: 'json', remote: 'undefined', branch: 'undefined' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitGetUserEmail:
  path:     /git/getuseremail/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::getUserEmailAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitLog:
  path:     /git/log/{site}/{repository}/{range}/{detail}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::logAction', _format: 'json', range: '1', detail: 'oneline' }

gitSetUserEmail:
  path:     /git/setuseremail/{userEmail}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::setUserEmailAction', _format: 'json' }

gitGetUserName:
  path:     /git/getusername/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::getUserNameAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitSetUserName:
  path:     /git/setusername/{userName}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::setUserNameAction', _format: 'json' }

gitPick:
  path:     /git/pick/{site}/{repository}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::pickAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitPull:
  path:     /git/pull/{site}/{repository}/{remote}/{branch}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::pullAction', _format: 'json', remote: 'undefined', branch: 'undefined' }

gitRepositories:
  path:     /git/list/{site}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::listAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

gitReset:
  path:     /git/reset/{site}/{repository}/{remote}/{branch}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::resetAction', _format: 'json', remote: 'undefined', branch: 'undefined' }

gitRevList:
  path:     /git/rev-list/{site}/{repository}/{range}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::revListAction', _format: 'json'}

gitStatus:
  path:     /git/status/{site}/{repository}/{range}/{detail}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::logAction', _format: 'json', range: '1', detail: 'oneline' }

gitTag:
  path:     /git/tag/{site}/{repository}/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\GitRepositoryController::tagAction', _format: 'json' }

version:
  path:     /version/{_format}
  defaults: { _controller: '\MaxServ\Typo3Local\VersionController::listAction', _format: 'json' }
  requirements: { _format: 'html|json', _method: 'GET' }

#default:
#  path:     /
#  defaults: { _controller: '\MaxServ\Typo3Local\IndexController::indexAction' }
#  requirements: { _method: 'GET' }
