# routes.yml
sites:
    path:     /site/list
    defaults: { controller: '\MaxServ\Typo3Local\SiteController', action: 'listAction', format: 'json' }

gitRepositories:
    path:     /git/list/{site}
    defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'listAction', format: 'json' }

gitStatus:
    path:     /git/status/{site}/{repository}/{range}/{detail}
    defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'statusAction', format: 'json', range: '1', detail: 'oneline' }

version:
    path:     /version
    defaults: { controller: '\MaxServ\Typo3Local\VersionController', action: 'listAction', format: 'json' }
