# routes.yml
sites:
  path:     /site/list
  defaults: { controller: '\MaxServ\Typo3Local\SiteController', action: 'listAction', format: 'json' }

gitBranch:
  path:     /git/branch/{site}/{repository}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'branchAction', format: 'json' }

gitClean:
  path:     /git/clean/{site}/{repository}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'cleanAction', format: 'json' }

gitCheckout:
  path:     /git/checkout/{site}/{repository}/{change}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'checkoutAction', format: 'json' }

gitFetch:
  path:     /git/fetch/{site}/{repository}/{remote}/{branch}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'fetchAction', format: 'json', remote: 'origin', branch: 'master' }

gitGetUserEmail:
  path:     /git/getuseremail
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'getUserEmailAction', format: 'json' }

gitSetUserEmail:
  path:     /git/setuseremail/{userEmail}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'setUserEmailAction', format: 'json' }

gitGetUserName:
  path:     /git/getusername
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'getUserNameAction', format: 'json' }

gitSetUserName:
  path:     /git/setusername/{userName}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'setUserNameAction', format: 'json' }

gitPick:
  path:     /git/pick/{site}/{repository}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'pickAction', format: 'json' }

gitPull:
  path:     /git/pull/{site}/{repository}/{remote}/{branch}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'pullAction', format: 'json', remote: 'origin', branch: 'master' }

gitRepositories:
  path:     /git/list/{site}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'listAction', format: 'json' }

gitReset:
  path:     /git/reset/{site}/{repository}/{remote}/{branch}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'resetAction', format: 'json', remote: 'origin', branch: 'master' }

gitStatus:
  path:     /git/status/{site}/{repository}/{range}/{detail}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'statusAction', format: 'json', range: '1', detail: 'oneline' }

gitTag:
  path:     /git/tag/{site}/{repository}
  defaults: { controller: '\MaxServ\Typo3Local\GitRepositoryController', action: 'tagAction', format: 'json' }

version:
  path:     /version
  defaults: { controller: '\MaxServ\Typo3Local\VersionController', action: 'listAction', format: 'json' }

default:
  path:     /